In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# adding csv file using pandas

In [8]:
df = pd.read_csv(r"C:\Users\SANKET\OneDrive\sanket project\Ecommerce Purchases")

In [9]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73

In [10]:
# Finding NUll values

In [11]:
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [12]:
# Finding Datatypes

In [13]:
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [14]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73

In [15]:
# Name of all columns

In [16]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [17]:
# all information

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [19]:
# Max, Min, Mean

In [20]:
df['Purchase Price'].max()

99.99

In [21]:
df['Purchase Price'].min()

0.0

In [22]:
df['Purchase Price'].mean()

50.347302

In [23]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73

In [24]:
# Number of engineers

In [25]:
len(df[df['Job'].str.contains('engineer', case= False)])

984

In [26]:
# Number of Drilling Engineers

In [27]:
len(df[df['Job']== 'Drilling engineer'])

21

In [28]:
# Most number of jobs persons have puchases more than 97

In [29]:
df2 = df[df['Purchase Price'] >= 97]['Job'].max()
df2

'Youth worker'

In [30]:
# credit card = mastercard, purchase price more than 90, language= french

In [31]:
df[(df['Purchase Price'] >=90)& (df['Language']== 'fr')& (df['CC Provider']== 'Mastercard')]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
2664,"89433 Andrew Cape Apt. 070\nWest Amanda, WA 16...",26 FL,PM,Opera/9.68.(X11; Linux x86_64; it-IT) Presto/2...,"Lambert, Wagner and Cochran",3528623160395956,07/19,556,Mastercard,georgesmith@yahoo.com,Personnel officer,45.114.159.172,fr,94.08
2821,"54256 Wilson Islands Suite 165\nShawnshire, PA...",88 oA,PM,Opera/9.99.(Windows NT 5.1; en-US) Presto/2.9....,"Acosta, Johnson and Boyer",30387888190472,06/20,37,Mastercard,andrewmoore@hotmail.com,Fast food restaurant manager,141.119.4.30,fr,91.67
2958,"1274 Rubio Place\nIsaiahville, NY 31551-2817",77 ef,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Williams LLC,6011058673376580,09/22,890,Mastercard,johnsonjulia@yahoo.com,Emergency planning/management officer,125.41.250.165,fr,90.76
3973,"209 Mcclain Spur Suite 965\nPort Angelastad, A...",42 bW,PM,Mozilla/5.0 (Windows 98; sl-SI; rv:1.9.1.20) G...,"Carter, Soto and Lewis",3158467000063185,11/20,944,Mastercard,blackchelsea@hotmail.com,"Engineer, communications",234.10.80.176,fr,99.54
4347,Unit 3829 Box 1760\nDPO AA 62327-1931,44 Qy,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Blair-Alvarez,4997361817318,07/19,1,Mastercard,oliverkevin@gmail.com,Legal secretary,206.116.204.236,fr,92.66
5651,"669 William Ranch Suite 352\nDanielhaven, AL 8...",80 nw,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows 98;...,Floyd-Castro,4412893819444,07/26,837,Mastercard,randysolomon@gmail.com,"Buyer, industrial",7.26.147.10,fr,99.02
6263,"PSC 1273, Box 3037\nAPO AA 11854-3422",93 HJ,PM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Fisher-Guerrero,4363719050674,04/24,592,Mastercard,david10@dodson-warner.com,Tree surgeon,158.196.81.143,fr,99.92
6865,"7223 Michael Fields\nRoberttown, OK 51852",35 OM,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_4...,"Hernandez, Guzman and Fisher",4817656635201,06/19,18,Mastercard,jessicawalker@hotmail.com,Dealer,45.83.132.77,fr,92.80
8980,"640 Williams Highway\nNew Kennethtown, SC 0031...",81 Yn,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,Moody-Gilbert,589348991250,06/18,456,Mastercard,epowell@torres-day.com,Musician,102.32.63.82,fr,92.58
9297,"PSC 6924, Box 9684\nAPO AA 40806",24 Zf,PM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Brown PLC,30523287595727,03/19,2505,Mastercard,william86@hotmail.com,"Scientist, research (life sciences)",86.78.219.254,fr,95.07

In [32]:
# job profession = Scientist, research (life sciences)

In [33]:
df[df['Job']== 'Scientist, research (life sciences)']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
28,"50533 Cooper Cliffs\nNorth Jonathanberg, MD 20482",17 kP,PM,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,Reed Inc,180026477662982,11/24,16,JCB 15 digit,khandeborah@yahoo.com,"Scientist, research (life sciences)",142.131.235.225,es,70.75
1878,"1188 Henry Knolls\nNorth Ryanport, AK 32829",43 lf,PM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,"Maldonado, Blake and Mejia",6011773134764543,02/23,899,Diners Club / Carte Blanche,telliott@gonzalez.com,"Scientist, research (life sciences)",146.182.88.73,de,93.20
2026,7047 Christensen Estates Suite 003\nPort Bethf...,09 Ch,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Soto Group,378369392191964,02/20,316,VISA 13 digit,wiseallen@yahoo.com,"Scientist, research (life sciences)",20.94.114.124,en,76.97
2050,"7918 Cindy Turnpike Apt. 239\nSarahport, NH 66356",42 pP,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_5_7) A...,"Moyer, Powell and Ruiz",4373713668870081,07/26,324,VISA 13 digit,cookdwayne@hotmail.com,"Scientist, research (life sciences)",210.8.83.160,fr,73.25
2727,"4398 Caldwell Loop\nSouth Michelle, RI 28387",90 EU,PM,Opera/9.12.(X11; Linux i686; sl-SI) Presto/2.9...,Washington-Kemp,346036086085500,01/24,547,VISA 16 digit,nathanrodriguez@freeman.com,"Scientist, research (life sciences)",156.124.99.208,ru,55.37
3617,USS Johnson\nFPO AP 00291,06 ir,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_9...,"Shelton, Terry and Byrd",630463876817,04/22,1173,VISA 16 digit,oclark@robinson.com,"Scientist, research (life sciences)",212.106.242.206,zh,46.38
3784,"031 Ariel Summit Apt. 510\nLake Karenview, CA ...",36 dz,PM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Lambert-Mitchell,373484023446599,11/24,998,American Express,james32@hotmail.com,"Scientist, research (life sciences)",244.130.1.225,zh,15.84
3956,"831 Lin Land\nEast Tiffanyland, ID 09083-6124",55 bw,PM,Mozilla/5.0 (Windows NT 6.2; sl-SI; rv:1.9.0.2...,"Chen, Walker and Graham",676338418814,07/19,635,JCB 15 digit,lindsaygarcia@hotmail.com,"Scientist, research (life sciences)",236.206.226.40,fr,30.03
3960,"44657 Anna Green Suite 251\nFrankland, LA 5512...",82 Id,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Fletcher-Nielsen,5575512432975231,04/18,363,JCB 16 digit,jonathan63@yahoo.com,"Scientist, research (life sciences)",42.46.217.167,es,7.19
4003,"152 Garcia Highway\nEast Jennifer, WV 66664",24 fl,AM,Opera/8.48.(X11; Linux x86_64; sl-SI) Presto/2...,Valenzuela Ltd,30013963507378,03/18,476,VISA 16 digit,lwheeler@mathews.org,"Scientist, research (life sciences)",114.76.242.219,es,91.74
4257,"537 Martin Shoals Suite 967\nJohnburgh, IN 62808",66 Ir,AM,Mozilla/5.0 (Windows; U; Windows 98) AppleWebK...,Palmer-Miller,3112377902098616,07/18,29,Diners Club / Carte Blanche,markhale@lee.info,"Scientist, research (life sciences)",156.194.86.28,de,1.38
4318,"PSC 2572, Box 5579\nAPO AP 96906-3249",62 gx,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_4 rv...,"Levine, Robertson and Taylor",6011793499098535,10/23,663,JCB 16 digit,richraymond@smith.com,"Scientist, research (life sciences)",77.5.81.45,en,10.67
4552,USNS Brown\nFPO AP 13483-4651,88 lB,AM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_5; r...,Jacobs and Sons,503801275929,08/21,441,Maestro,brittany50@yahoo.com,"Scientist, research (life sciences)",189.216.102.65,pt,65.22
4730,"92025 Stanley Light\nWest Jenniferton, HI 3058...",34 EA,PM,Mozilla/5.0 (compatible; MSIE 5.0; Windows 98;...,Martin-Curtis,4547689851026,03/24,948,Discover,norrisbrandi@nixon-james.com,"Scientist, research (life sciences)",104.73.249.16,pt,37.18
5103,"5417 Hess Fort Apt. 955\nNew James, NV 83909-6361",08 Uv,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows 95;...,Castillo-Rhodes,180027678867271,01/25,709,VISA 16 digit,escott@murphy.net,"Scientist, research (life sciences)",217.203.68.53,ru,64.54
5825,USCGC Jones\nFPO AA 01851,14 GU,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gutierrez Group,4492012204534350,11/25,404,Diners Club / Carte Blanche,uorozco@scott.info,"Scientist, research (life sciences)",241.184.25.101,pt,18.22
6186,"3866 Lara Rapid\nLake Curtis, ME 41910",93 zX,AM,Mozilla/5.0 (Windows NT 6.1; it-IT; rv:1.9.1.2...,Kelly-Watts,4442201917250609,12/21,204,JCB 16 digit,nicholasmoore@anderson-rodriguez.org,"Scientist, research (life sciences)",93.227.165.199,zh,88.28
6276,"19510 Jesse Turnpike\nRaymondview, NV 09504-5749",85 qU,AM,Opera/9.19.(Windows NT 5.2; en-US) Presto/2.9....,Martinez-Arnold,3528196379886685,07/26,922,Maestro,tracey53@sanchez.com,"Scientist, research (life sciences)",6.177.101.254,zh,58.33
8913,"2058 Jessica Port\nJamesmouth, WI 45687-6440",48 aP,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows CE;...,"Newman, Hall and Morrison",5452162290323278,05/19,98,JCB 16 digit,qbarr@west.com,"Scientist, research (life sciences)",139.133.15.39,de,32.51
9297,"PSC 6924, Box 9684\nAPO AA 40806",24 Zf,PM,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Brown PLC,30523287595727,03/19,2505,Mastercard,william86@hotmail.com,"Scientist, research (life sciences)",86.78.219.254,fr,95.07
9563,"30260 Trevor Circle Apt. 132\nNew Lisa, GA 515...",33 qT,AM,Mozilla/5.0 (Windows 98; Win 9x 4.90) AppleWeb...,"Robertson, Perry and Vance",4352914341199170,08/25,323,American Express,wclark@yahoo.com,"Scientist, research (life sciences)",234.107.226.63,ru,87.03
9983,"PSC 5678, Box 4503\nAPO AP 94998-5546",79 cd,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Hall-Cantu,343856674589081,04/23,206,JCB 16 digit,jacksonmanuel@rodriguez-welch.com,"Scientist, research (life sciences)",245.22.66.225,de,47.70

In [34]:
# list of job = scientist

In [35]:
df[df['Job'].str.contains('Scientist', case= False)]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63
28,"50533 Cooper Cliffs\nNorth Jonathanberg, MD 20482",17 kP,PM,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,Reed Inc,180026477662982,11/24,16,JCB 15 digit,khandeborah@yahoo.com,"Scientist, research (life sciences)",142.131.235.225,es,70.75
70,Unit 9635 Box 0238\nDPO AE 55910-7730,76 NA,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,Garcia-Leon,4754420478628,09/25,65,JCB 16 digit,kristi17@rodgers-morris.biz,Forensic scientist,213.132.122.145,ru,78.91
114,Unit 0282 Box 9769\nDPO AP 05162-2277,72 zO,AM,Mozilla/5.0 (Windows NT 6.0) AppleWebKit/5331 ...,Mcbride and Sons,210064795352915,08/18,9413,Maestro,matthew50@hotmail.com,Research scientist (maths),205.48.101.138,pt,77.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9725,"379 Derek Flats\nEast Juliestad, AR 17361-7304",86 Zu,PM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Smith, Gonzalez and Tran",210076469997312,02/22,141,Maestro,jessicablack@gmail.com,Research scientist (physical sciences),202.128.193.116,fr,95.71
9826,"2040 Bauer Plains\nNew Oliviafurt, OK 04192-8492",07 oo,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_5_1) A...,Dixon-Hill,180099665523670,11/21,522,Maestro,martinezlisa@gmail.com,"Scientist, clinical (histocompatibility and im...",130.31.90.189,it,18.73
9876,"4958 Richard Estate\nWilsontown, ME 19966-4472",30 su,PM,Opera/8.95.(X11; Linux i686; en-US) Presto/2.9...,Marshall-Clark,3088667674419606,05/26,246,American Express,wpeck@robinson-alvarez.info,Research scientist (medical),50.12.226.70,it,65.27
9923,"313 Harris Drives Apt. 578\nTommyview, LA 1716...",15 VO,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,"Duffy, Sharp and Logan",502077008782,12/16,67,American Express,jonesandrew@hayes.info,Marine scientist,41.201.201.36,en,63.61
9983,"PSC 5678, Box 4503\nAPO AP 94998-5546",79 cd,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Hall-Cantu,343856674589081,04/23,206,JCB 16 digit,jacksonmanuel@rodriguez-welch.com,"Scientist, research (life sciences)",245.22.66.225,de,47.70

In [36]:
#time value counts

In [37]:
df['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [38]:
# Number of credit cards that expiring in 2022

In [39]:
def fun():
    count= 0
    for date in df['CC Exp Date']:
        if date.split('/')[1]=='22':
            count= count+1
    print(count)

In [40]:
fun()

996

In [41]:
# credit card expiring in 2026

In [42]:
df[df['CC Exp Date'].apply(lambda x:x[3:]=='26')]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
11,"349 Laurie Parks\nThomasview, ID 08970",30 kK,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,Kim-Oliver,869975209012056,06/26,9717,JCB 15 digit,johnnymiller@coleman.com,Diagnostic radiographer,128.222.40.234,en,19.26
12,"733 Heather Rest Apt. 670\nBoltonport, UT 78662",69 DO,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 ...,Moore-Martin,5115990487067905,05/26,119,VISA 16 digit,tholt@hotmail.com,"Surveyor, quantity",236.71.234.240,en,39.65
17,950 Jacqueline Village Apt. 592\nPort Kimberly...,23 Rh,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Fernandez, Melton and Gilbert",3337515540944084,01/26,771,American Express,stacymitchell@hall.com,"Designer, jewellery",223.25.125.61,el,58.68
40,"821 Adams Courts Apt. 568\nNorth Nicole, MS 03...",35 gn,AM,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,Weiss Group,348836222401711,05/26,667,Voyager,hernandezevelyn@dickerson.com,Tourist information centre manager,102.225.220.122,pt,87.68
45,"096 Edwards Valleys Suite 917\nPerkinsberg, LA...",07 Cd,PM,Mozilla/5.0 (Windows NT 6.2) AppleWebKit/5312 ...,Jackson-Allen,869978354045368,03/26,406,American Express,gregorygarner@chambers.com,Games developer,222.242.66.78,es,18.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9928,"210 Patterson Port Apt. 265\nHendrixbury, GA 7...",98 Cm,PM,Opera/8.42.(X11; Linux x86_64; sl-SI) Presto/2...,Harvey-Hampton,30565321163079,03/26,817,JCB 15 digit,robert57@davis.com,Best boy,227.70.41.50,ru,9.99
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9965,"2268 Austin Village Apt. 542\nWest Meghan, CA ...",03 hK,AM,Opera/8.21.(Windows NT 5.1; en-US) Presto/2.9....,Berry-Anderson,5397000698055050,02/26,836,American Express,michellejenkins@hotmail.com,Commercial/residential surveyor,149.81.82.218,es,61.46
9967,"409 Holland Drives\nWhitetown, ME 78654",38 aX,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Singleton Inc,869944453111857,04/26,602,Diners Club / Carte Blanche,gina95@gmail.com,Television camera operator,120.205.69.231,es,98.42
9974,"500 Powell Rapid Apt. 114\nClarkfort, FL 70488",48 is,AM,Mozilla/5.0 (Windows 95) AppleWebKit/5312 (KHT...,Griffin-Lopez,630407297302,04/26,627,VISA 16 digit,paula72@yahoo.com,Sports therapist,166.220.170.176,el,66.45

In [43]:
# Finding most widely used email address

In [44]:
list0 = []
for email in df['Email']:
    list0.append(email.split('@')[1])

In [45]:
df['new'] = list0

In [46]:
df.head(2)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,new
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,reed.com

In [47]:
df['new'].value_counts()

hotmail.com            1638
yahoo.com              1616
gmail.com              1605
smith.com                42
williams.com             37
                       ...
booker.com                1
woods-allen.biz           1
richards-wilson.com       1
morris-thomas.com         1
wade-garner.com           1
Name: new, Length: 3416, dtype: int64

In [48]:
#value count using lambda function

In [49]:
df['Email'].apply(lambda x:x.split('@')[1]).value_counts().head(10)

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
brown.com         29
johnson.com       29
davis.com         25
jones.com         25
martinez.com      19
Name: Email, dtype: int64